[package]
name = "digilogic_routing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]

digilogic_core = { path = "../digilogic_core" }
