[package]
name = "digilogic_routing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bevy_ecs.workspace = true
bevy_app.workspace = true
bevy_hierarchy.workspace = true

digilogic_core = { path = "../digilogic_core" }
