/*
   Copyright 2024 Ryan "rj45" Sanche

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
  char *buffer = 0;

  FILE *fp = fopen("res/assets.zip", "rb");
  if (fp == NULL) {
    fprintf(stderr, "File not found\n");
    return 1;
  }
  fseek(fp, 0, SEEK_END);
  size_t length = ftell(fp);
  fseek(fp, 0, SEEK_SET);
  buffer = malloc(length + 1);
  if (fread(buffer, 1, length, fp) != length) {
    fclose(fp);
    free(buffer);
    fprintf(stderr, "Error reading file\n");
    return 1;
  }
  fclose(fp);

  printf("// This file was generated by gen.c from res/assets.zip -- DO NOT "
         "EDIT\n\n");
  printf("unsigned int assets_zip_len = %td;\n", length);
  printf("const unsigned char assets_zip[] = {\n    ");
  for (int i = 0; i < length; i++) {
    printf("0x%02x,", buffer[i] & 0xff);
    if (i % 10 == 9) {
      printf("\n    ");
    }
  }
  printf("\n};\n");
  free(buffer);

  return 0;
}